keyword = "magenta"
keyword2 = "dark_red"
function = "blue"
type = "cyan"
symbol = "red"
macro = "dark_yellow"
literal = "green"
lifetime = "dark_magenta"
comment = "dark_grey"
const = "dark_green"
ident = "dark_blue"
paren_rainbow = true
